import React from 'react';
import { Download, RefreshCw, CheckCircle } from 'lucide-react';
import { motion } from 'motion/react';

interface Step3Props {
  pdfBytes: Uint8Array;
  visualCvBase64: string;
  onRestart: () => void;
}

export const Step3Result: React.FC<Step3Props> = ({ pdfBytes, visualCvBase64, onRestart }) => {
  const handleDownload = () => {
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Visual_Resume_ATS.pdf';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="max-w-5xl mx-auto w-full"
    >
      <div className="text-center mb-12">
        <div className="w-16 h-16 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
          <CheckCircle className="w-8 h-8 text-emerald-400" />
        </div>
        <h2 className="text-4xl font-bold text-white mb-4">Your Resume is Ready!</h2>
        <p className="text-zinc-400 text-lg">
          Beautifully designed for humans, perfectly structured for ATS robots.
        </p>
      </div>

      <div className="grid md:grid-cols-2 gap-12 items-start">
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 shadow-2xl">
          <div className="aspect-[3/4] w-full bg-zinc-950 rounded-xl overflow-hidden border border-zinc-800">
            <img 
              src={`data:image/png;base64,${visualCvBase64}`} 
              alt="Visual CV Preview" 
              className="w-full h-full object-contain"
              referrerPolicy="no-referrer"
            />
          </div>
        </div>

        <div className="space-y-8">
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8">
            <h3 className="text-xl font-semibold text-white mb-4">What's inside?</h3>
            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <div className="w-6 h-6 rounded-full bg-blue-500/20 flex items-center justify-center shrink-0 mt-0.5">
                  <div className="w-2 h-2 bg-blue-400 rounded-full" />
                </div>
                <div>
                  <p className="text-zinc-200 font-medium">High-Res Visual Design</p>
                  <p className="text-sm text-zinc-500">Generated by Nano Banana Pro.</p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="w-6 h-6 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0 mt-0.5">
                  <div className="w-2 h-2 bg-emerald-400 rounded-full" />
                </div>
                <div>
                  <p className="text-zinc-200 font-medium">Invisible ATS Text Layer</p>
                  <p className="text-sm text-zinc-500">Ensures 100% readability by HR software.</p>
                </div>
              </li>
            </ul>
          </div>

          <div className="space-y-4">
            <button
              onClick={handleDownload}
              className="w-full py-4 px-6 bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-medium text-lg shadow-lg shadow-blue-900/20 flex items-center justify-center gap-2 transition-all"
            >
              <Download className="w-5 h-5" /> Download ATS-Friendly PDF
            </button>
            <button
              onClick={onRestart}
              className="w-full py-4 px-6 bg-zinc-800 hover:bg-zinc-700 text-white rounded-xl font-medium flex items-center justify-center gap-2 transition-all"
            >
              <RefreshCw className="w-5 h-5" /> Create Another
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
};
